Add PUSHSLICE xN_ instructions
tonlabs/TON-Compiler pull request #168
Opened 2020-10-27 08:38 UTC by akiramenai

2020-10-27 10:13 UTC, azhogin commented on llvm/lib/Target/TVM/TVMLiteralInstrInfo.td
> +let mayLoad = 1 in
Why `mayLoad`? As far as I understand, this instruction is pure constant generation.
Is it technically necessary?

2020-10-29 15:49 UTC, azhogin requested changes
Why `mayLoad` for PUSHSLICE_EMPTY?

2020-11-08 10:53 UTC, akiramenai commented on llvm/lib/Target/TVM/TVMLiteralInstrInfo.td
> +let mayLoad = 1 in
`NEWC` may load (see your own comment about coroutines), the pattern added uses `NEWC` so LLVM requires to propagate mayLoad

2020-11-23 06:35 UTC, azhogin approved these changes

2020-11-23 06:35 UTC, merged