Add DefineUndef pass
tonlabs/TON-Compiler pull request #175
Opened 2020-11-14 20:38 UTC by akiramenai

The pass is to define undef i257, cell and slice in STU, STI, STREF and
STSLICE instructions, thus prevent a codegen issue.

2020-11-16 06:45 UTC, azhogin requested changes
Looks like you forgot to add "TVMDefineUndef.cpp".

2020-11-20 01:19 UTC, azhogin commented on llvm/lib/Target/TVM/TVMDefineUndef.cpp
> +static bool defineStslice(Instruction &I) {
Why not `int_tvm_pushslice_empty` for creating of empty slice?

2020-11-20 09:05 UTC, akiramenai commented on llvm/lib/Target/TVM/TVMDefineUndef.cpp
> +static bool defineStslice(Instruction &I) {
I actually rely on https://github.com/tonlabs/TON-Compiler/pull/168 to do the job. I don't even sure that we need `int_tvm_pushslice_empty` in the first place because it's expressable in terms of other intrinsics (it can be substituted with a library function) and the less intrinsic we introduce the better. That's the thought. I don't mind however to switch to `int_tvm_pushslice_empty` if you think otherwise.
Aside from that, I think we can create a ticket to get rid of `mayLoad` and merge 168 to not to wait too long.

2020-11-20 10:46 UTC, azhogin approved these changes

2020-11-20 10:46 UTC, merged